# True for training, False for prediction
is_training: True

# True for resuming training, False for new training
resume_training: True

# train parameters
train_dataset_name: "dataset-split2"
dataset_yaml_name: "dataset.yaml"
custom_cfg_name: "custom_train_config.yaml"

# predict parameters
test_dataset_name: "Hamza_Hoca_Dataset"
patient_name: ["Ömer_Faruk_Kiraz"]

# True for Telefon, False for Ekran
is_patient_dir_telefon: False

# True for prediction with videos, 
# False for prediction with image folders
is_test_dir_video: True
test_video_name: "Vid0065"

# weight parameters
runs_dirname: ["runs", "detect"]
train_folder_name: "train_yolov8s_30_epoch_telefon"
weights_folder_name: "weights"
yolo_weight: "yolov8s.pt"

# YOLO Predict function arguments
imgsz: [1920, 1080]
save: True
stream: False
line_width: 2